"""
Google Sheet CSV → knowledge_items SQL insert script
Kullanım:
  python scripts/csv_to_kb_sql.py data/eurostar/ulkeler.csv ulkeler
  python scripts/csv_to_kb_sql.py data/eurostar/sss.csv faq
  python scripts/csv_to_kb_sql.py data/eurostar/fiyatlar.csv pricing

Çıktı: sql/04_eurostar_kb.sql dosyasına eklenir
"""
import csv
import json
import sys
import uuid
import os
from pathlib import Path

ORG_ID = "a1b2c3d4-0000-0000-0000-000000000001"
OUTPUT_FILE = Path(__file__).parent.parent / "sql" / "04_eurostar_kb.sql"

ITEM_TYPE_MAP = {
    "ulkeler": "country",
    "faq": "faq",
    "sss": "faq",
    "fiyatlar": "pricing",
    "programlar": "program",
    "ekip": "team_member",
}


def detect_columns(headers):
    """CSV header'larına göre hangi kolonun ne olduğunu tahmin et."""
    h = [h.lower().strip() for h in headers]
    mapping = {}

    # Başlık / soru alanı
    for candidate in ["soru", "baslik", "başlık", "title", "question", "ülke", "ulke", "country", "program"]:
        for i, col in enumerate(h):
            if candidate in col:
                mapping["title"] = headers[i]
                break
        if "title" in mapping:
            break

    # Açıklama / cevap alanı
    for candidate in ["cevap", "aciklama", "açıklama", "description", "answer", "bilgi", "detay"]:
        for i, col in enumerate(h):
            if candidate in col:
                mapping["description"] = headers[i]
                break
        if "description" in mapping:
            break

    return mapping


def process_csv(filepath: str, item_type_hint: str):
    item_type = ITEM_TYPE_MAP.get(item_type_hint.lower(), "faq")
    inserts = []

    with open(filepath, encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        headers = reader.fieldnames or []
        col_map = detect_columns(headers)

        title_col = col_map.get("title")
        desc_col = col_map.get("description")

        if not title_col:
            print(f"UYARI: Başlık kolonu bulunamadı. Mevcut kolonlar: {headers}")
            print("Devam etmek için: scripts/csv_to_kb_sql.py <dosya> <tip> --title <kolon> --desc <kolon>")
            sys.exit(1)

        for row in reader:
            title = row.get(title_col, "").strip()
            if not title:
                continue

            # description_for_ai: varsa desc kolonu, yoksa tüm row'u birleştir
            if desc_col:
                description = row.get(desc_col, "").strip()
            else:
                description = " | ".join(
                    f"{k}: {v}" for k, v in row.items()
                    if v and v.strip() and k != title_col
                )

            # data JSONB: kalan tüm kolonlar
            data = {k: v.strip() for k, v in row.items() if v and v.strip()}

            # Tags: item_type + ülke varsa ülke adı
            tags = [item_type]
            if item_type == "country":
                tags.append(title.lower().replace(" ", "_"))

            item_id = str(uuid.uuid4())

            inserts.append({
                "id": item_id,
                "organization_id": ORG_ID,
                "item_type": item_type,
                "title": title,
                "description_for_ai": description,
                "data": data,
                "tags": tags,
            })

    return inserts


def to_sql(inserts: list) -> str:
    lines = [
        "-- Auto-generated by csv_to_kb_sql.py",
        "-- Eurostar Knowledge Items",
        "",
    ]

    for item in inserts:
        tags_sql = "ARRAY[" + ",".join(f"'{t}'" for t in item["tags"]) + "]"
        data_json = json.dumps(item["data"], ensure_ascii=False).replace("'", "''")
        title_safe = item["title"].replace("'", "''")
        desc_safe = item["description_for_ai"].replace("'", "''")

        lines.append(f"""INSERT INTO public.knowledge_items
  (id, organization_id, item_type, title, description_for_ai, data, tags, is_active)
VALUES (
  '{item["id"]}',
  '{item["organization_id"]}',
  '{item["item_type"]}',
  '{title_safe}',
  '{desc_safe}',
  '{data_json}'::jsonb,
  {tags_sql},
  true
) ON CONFLICT DO NOTHING;
""")

    return "\n".join(lines)


def main():
    if len(sys.argv) < 3:
        print("Kullanım: python scripts/csv_to_kb_sql.py <csv_dosyasi> <tip>")
        print("Tipler: ulkeler, faq, fiyatlar, programlar")
        sys.exit(1)

    filepath = sys.argv[1]
    item_type_hint = sys.argv[2]

    if not os.path.exists(filepath):
        print(f"Dosya bulunamadı: {filepath}")
        sys.exit(1)

    print(f"İşleniyor: {filepath} ({item_type_hint})")
    inserts = process_csv(filepath, item_type_hint)
    print(f"{len(inserts)} kayıt bulundu")

    sql_content = to_sql(inserts)

    # Mevcut dosyaya ekle veya yeni oluştur
    mode = "a" if OUTPUT_FILE.exists() else "w"
    with open(OUTPUT_FILE, mode, encoding="utf-8") as f:
        if mode == "w":
            f.write("-- ═══════════════════════════════════════════════════\n")
            f.write("-- Eurostar Knowledge Base — CSV Import\n")
            f.write("-- ═══════════════════════════════════════════════════\n\n")
        f.write(sql_content)

    print(f"SQL yazıldı: {OUTPUT_FILE}")
    print(f"\nSonraki adım: Supabase SQL Editor'da sql/04_eurostar_kb.sql çalıştır")


if __name__ == "__main__":
    main()
